class QuestionScripts {
  Map Questions = {
    '1': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': 'Was the blonde-haired child sitting?',
      'Q61': 'Yes',
      'Q62': 'No',
      'Q63': 'Unknown',
      'Q6A': 'No',
      //
      'Q7': 'How many blue cars did the children play with?',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': 'How many trucks were the children playing with?',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '2',
      //
      'Q9': 'Was the door open?',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': 'How many floors did the house have?',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    '2': {
      'Q1': 'What color was the main building?',
      'Q11': 'Red',
      'Q12': 'Blue',
      'Q13': 'Yellow',
      'Q1A': 'Red',
      //
      'Q2': 'How many bicycles were parked nearby?',
      'Q21': '1',
      'Q22': '2',
      'Q23': '3',
      'Q2A': '2',
      //
      'Q3': 'Were there any benches? How many?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '2',
      //
      'Q4': 'What color was the sky?',
      'Q41': 'Blue',
      'Q42': 'Gray',
      'Q43': 'White',
      'Q4A': 'Blue',
      //
      'Q5': 'Were there any clouds? What shape were they?',
      'Q51': 'Yes, Butterfly',
      'Q52': 'No',
      'Q53': 'Yes, Circle',
      'Q5A': 'Yes, Butterfly',
      //
      'Q6': 'Was there a playground? What equipment did it have?',
      'Q61': 'Yes, Swing and Slide',
      'Q62': 'No',
      'Q63': 'Yes, Sandbox',
      'Q6A': 'Yes, Swing and Slide',
      //
      'Q7': 'How many people were sitting on benches?',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '1',
      //
      'Q8': 'Was there a water fountain? What color was it?',
      'Q81': 'Yes, Blue',
      'Q82': 'No',
      'Q83': 'Yes, White',
      'Q8A': 'No',
      //
      'Q9': 'Were there any streetlights? How many?',
      'Q91': '1',
      'Q92': '2',
      'Q93': '3',
      'Q9A': '2',
      //
      'Q10': 'Were there any signs? What did they say?',
      'Q101': 'Yes, Stop',
      'Q102': 'No',
      'Q103': 'Yes, Go',
      'Q10A': 'Yes, Stop',
    },
    '3': {
      'Q1': 'What was the color of the shop\'s sign?',
      'Q11': 'White',
      'Q12': 'Red',
      'Q13': 'Blue',
      'Q1A': 'White',
      //
      'Q2': 'How many customers were inside the shop?',
      'Q21': '2',
      'Q22': '4',
      'Q23': '6',
      'Q2A': '4',
      //
      'Q3': 'Was there a clock visible? What time did it show?',
      'Q31': 'Yes, 10 AM',
      'Q32': 'No',
      'Q33': 'Yes, 11 AM',
      'Q3A': 'Yes, 11 AM',
      //
      'Q4': 'Were there any sale banners? What did they advertise?',
      'Q41': 'Yes, 50% Off',
      'Q42': 'No',
      'Q43': 'Yes, Buy 1 Get 1',
      'Q4A': 'Yes, 50% Off',
      //
      'Q5': 'How many cash registers were open?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '3',
      //
      'Q6': 'Were there any flowers in vases? What colors?',
      'Q61': 'Yes, Red',
      'Q62': 'No',
      'Q63': 'Yes, Red and White',
      'Q6A': 'Yes, Red and White',
      //
      'Q7': 'Was there a basket of fruit? What types of fruit were in it?',
      'Q71': 'Yes, Apples and Bananas',
      'Q72': 'No',
      'Q73': 'Yes, Oranges',
      'Q7A': 'Yes, Apples and Bananas',
      //
      'Q8': 'Were there any employees? What were they wearing?',
      'Q81': 'Yes, Uniforms',
      'Q82': 'No',
      'Q83': 'Yes, Black Shirts',
      'Q8A': 'Yes, Black Shirts',
      //
      'Q9': 'Was there a cat or dog inside the shop?',
      'Q91': 'Cat',
      'Q92': 'Dog',
      'Q93': 'No',
      'Q9A': 'Cat',
      //
      'Q10': 'How many lights were open?',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '3',
    },
    '4': {
      'Q1': 'What color was the Ferris wheel?',
      'Q11': 'Red',
      'Q12': 'Blue',
      'Q13': 'Yellow',
      'Q1A': 'Blue',
      //
      'Q2': 'How many people were waiting in line for the roller coaster?',
      'Q21': '1',
      'Q22': '2',
      'Q23': '3',
      'Q2A': '3',
      //
      'Q3': 'Was there a carousel in the picture? What animals were on it?',
      'Q31': 'Yes, Horses',
      'Q32': 'No',
      'Q33': 'Yes, Lions',
      'Q3A': 'Yes, Horses',
      //
      'Q4': 'Were there any food stalls visible? What kind of food were they selling?',
      'Q41': 'Yes, Popcorn',
      'Q42': 'No',
      'Q43': 'Yes, Hot Dogs',
      'Q4A': 'No',
      //
      'Q5': 'How many balloons were being held by the clown?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': 'What are the children eating?',
      'Q61': 'Cotton Candy',
      'Q62': 'Ice Cream',
      'Q63': 'Popcorn',
      'Q6A': 'Cotton Candy',
      //
      'Q7': 'How many children were holding cotton candy?',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': 'How many blue cotton candy?',
      'Q81': '1',
      'Q82': '2',
      'Q83': '0',
      'Q8A': '0',
      //
      'Q9': 'Was the carousel near the Ferris wheel or far from it?',
      'Q91': 'Near',
      'Q92': 'Far',
      'Q93': 'Next to it',
      'Q9A': 'Near',
      //
      'Q10': 'How many cars were there?',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '3',
    },
    '5': {
      'Q1': 'What color was the safari vehicle?',
      'Q11': 'Green',
      'Q12': 'Yellow',
      'Q13': 'Red',
      'Q1A': 'Green',
      //
      'Q2': 'How many people were in the safari vehicle?',
      'Q21': '2',
      'Q22': '4',
      'Q23': '6',
      'Q2A': '4',
      //
      'Q3': 'Was the elephant standing or walking? What was it doing?',
      'Q31': 'Standing',
      'Q32': 'Walking',
      'Q33': 'Running',
      'Q3A': 'Walking',
      //
      'Q4': 'How many giraffes were in the picture?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'Were there any zebras visible? How many?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': 'What color were the spots on the giraffe?',
      'Q61': 'Brown',
      'Q62': 'Black',
      'Q63': 'White',
      'Q6A': 'Brown',
      //
      'Q7': 'Was there a lion or any other big cat? What was it doing?',
      'Q71': 'Yes, Sleeping',
      'Q72': 'No',
      'Q73': 'Yes, Eating',
      'Q7A': 'Yes, Sleeping',
      //
      'Q8': 'Were there any birds in the picture? What kind?',
      'Q81': 'Yes, Parrots',
      'Q82': 'No',
      'Q83': 'Yes, Eagles',
      'Q8A': 'Yes, Parrots',
      //
      'Q9': 'Was the safari vehicle moving or stationary?',
      'Q91': 'Moving',
      'Q92': 'Stationary',
      'Q93': 'Parked',
      'Q9A': 'Moving',
      //
      'Q10': 'What was the landscape like? Were there trees, grass, or water?',
      'Q101': 'Trees',
      'Q102': 'Grass',
      'Q103': 'Water',
      'Q10A': 'Grass',
    },
    '6': {
      'Q1': 'How many beach umbrellas are there?',
      'Q11': '2',
      'Q12': '3',
      'Q13': '4',
      'Q1A': '3',
      //
      'Q2': 'What color is the lifeguard tower?',
      'Q21': 'Red',
      'Q22': 'Yellow',
      'Q23': 'Blue',
      'Q2A': 'Red',
      //
      'Q3': 'What color is the lifeguard’s shirt?',
      'Q31': 'Red',
      'Q32': 'Yellow',
      'Q33': 'White',
      'Q3A': 'Red',
      //
      'Q4': 'Does the lifeguard look happy or angry?',
      'Q41': 'Happy',
      'Q42': 'Angry',
      'Q43': 'Neutral',
      'Q4A': 'Happy',
      //
      'Q5': 'Are there any surfers? How many?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '2',
      //
      'Q6': 'Is the lifeguard tower on the right of the volleyball field?',
      'Q61': 'Yes',
      'Q62': 'No',
      'Q63': 'Next to it',
      'Q6A': 'Yes',
      //
      'Q7': 'How many people are playing volleyball?',
      'Q71': '2',
      'Q72': '4',
      'Q73': '6',
      'Q7A': '4',
      //
      'Q8': 'Is there a sandcastle? How many?',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '2',
      //
      'Q9': 'What color is the sky?',
      'Q91': 'Blue',
      'Q92': 'Gray',
      'Q93': 'White',
      'Q9A': 'Blue',
      //
      'Q10': 'Are there any boats in the water?',
      'Q101': 'Yes',
      'Q102': 'No',
      'Q103': 'Maybe',
      'Q10A': 'Yes',
      //
      'Q11': 'How many seagulls are flying?',
      'Q111': '1',
      'Q112': '2',
      'Q113': '3',
      'Q11A': '2',
      //
      'Q12': 'How many children are eating ice cream?',
      'Q121': '1',
      'Q122': '2',
      'Q123': '3',
      'Q12A': '3',
    },
    '7': {
      'Q1': 'How many skyscrapers are in the image?',
      'Q11': '2',
      'Q12': '3',
      'Q13': '4',
      'Q1A': '3',
      //
      'Q2': 'What color are the traffic lights?',
      'Q21': 'Red',
      'Q22': 'Yellow',
      'Q23': 'Green',
      'Q2A': 'Red',
      //
      'Q3': 'Are there any taxis? How many?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '2',
      //
      'Q4': 'What is the color of the bus?',
      'Q41': 'Red',
      'Q42': 'Blue',
      'Q43': 'Yellow',
      'Q4A': 'Blue',
      //
      'Q5': 'How many people are crossing the street?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '2',
      //
      'Q6': 'Is there a park in the scene? What is in it?',
      'Q61': 'Yes, Trees',
      'Q62': 'No',
      'Q63': 'Yes, Flowers',
      'Q6A': 'Yes, Trees',
      //
      'Q7': 'What time is it according to the clock tower?',
      'Q71': '10 AM',
      'Q72': '11 AM',
      'Q73': '12 PM',
      'Q7A': '11 AM',
      //
      'Q8': 'Are there any street performers? What are they doing?',
      'Q81': 'Yes, Singing',
      'Q82': 'No',
      'Q83': 'Yes, Dancing',
      'Q8A': 'Yes, Singing',
      //
      'Q9': 'What is advertised on the billboard?',
      'Q91': 'Movies',
      'Q92': 'Food',
      'Q93': 'Clothes',
      'Q9A': 'Movies',
      //
      'Q10': 'How many buses were passing by?',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '1',
    },
    '8': {
      'Q1': 'How many trees are in the picture?',
      'Q11': '1',
      'Q12': '2',
      'Q13': '3',
      'Q1A': '3',
      //
      'Q2': 'Are there any animals? What kind?',
      'Q21': 'Yes, Deer',
      'Q22': 'No',
      'Q23': 'Yes, Birds',
      'Q2A': 'Yes, Deer',
      //
      'Q3': 'What color are the flowers?',
      'Q31': 'Red',
      'Q32': 'Blue',
      'Q33': 'Yellow',
      'Q3A': 'Yellow',
      //
      'Q4': 'Is there a river?',
      'Q41': 'Yes',
      'Q42': 'No',
      'Q43': 'Maybe',
      'Q4A': 'Yes',
      //
      'Q5': 'How many hikers are there?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '2',
      //
      'Q6': 'Are there any birds? How many?',
      'Q61': 'Yes, 1',
      'Q62': 'Yes, 2',
      'Q63': 'No',
      'Q6A': 'Yes, 2',
      //
      'Q7': 'What season does it look like?',
      'Q71': 'Spring',
      'Q72': 'Summer',
      'Q73': 'Fall',
      'Q7A': 'Fall',
      //
      'Q8': 'Are there any mushrooms?',
      'Q81': 'Yes',
      'Q82': 'No',
      'Q83': 'Maybe',
      'Q8A': 'Yes',
      //
      'Q9': 'Is there a campsite? Where is it?',
      'Q91': 'Yes, Near the river',
      'Q92': 'No',
      'Q93': 'Yes, Near the trees',
      'Q9A': 'Yes, Near the trees',
      //
      'Q10': 'How many different types of plants can you see?',
      'Q101': '2',
      'Q102': '3',
      'Q103': '4',
      'Q10A': '4',
    },
    '9': {
      'Q1': 'How many cows are in the field?',
      'Q11': '1',
      'Q12': '2',
      'Q13': '3',
      'Q1A': '2',
      //
      'Q2': 'What color is the barn?',
      'Q21': 'Red',
      'Q22': 'Blue',
      'Q23': 'Yellow',
      'Q2A': 'Red',
      //
      'Q3': 'Are there any tractors? What color are they?',
      'Q31': 'Yes, Green',
      'Q32': 'No',
      'Q33': 'Yes, Red',
      'Q3A': 'Yes, Green',
      //
      'Q4': 'How many chickens are there?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '3',
      //
      'Q5': 'Is there a farmer? What is he/she doing?',
      'Q51': 'Yes, Feeding animals',
      'Q52': 'No',
      'Q53': 'Yes, Harvesting crops',
      'Q5A': 'Yes, Feeding animals',
      //
      'Q6': 'Are there any crops? What kind?',
      'Q61': 'Yes, Corn',
      'Q62': 'No',
      'Q63': 'Yes, Wheat',
      'Q6A': 'Yes, Corn',
      //
      'Q7': 'Where are the hay bales?',
      'Q71': 'In the barn',
      'Q72': 'In the field',
      'Q73': 'In the truck',
      'Q7A': 'In the field',
      //
      'Q8': 'Are there any fences? What color?',
      'Q81': 'Yes, White',
      'Q82': 'No',
      'Q83': 'Yes, Red',
      'Q8A': 'Yes, White',
      //
      'Q9': 'Where are the cows?',
      'Q91': 'In the field',
      'Q92': 'In the barn',
      'Q93': 'In the truck',
      'Q9A': 'In the field',
      //
      'Q10': 'Are there any horses? How many?',
      'Q101': 'Yes, 1',
      'Q102': 'Yes, 2',
      'Q103': 'No',
      'Q10A': 'Yes, 1',
    },
    '10': {
      'Q1': 'How many planets are visible?',
      'Q11': '1',
      'Q12': '2',
      'Q13': '3',
      'Q1A': '2',
      //
      'Q2': 'What color is the spaceship?',
      'Q21': 'White',
      'Q22': 'Black',
      'Q23': 'Red',
      'Q2A': 'White',
      //
      'Q3': 'Are there any astronauts? What are they doing?',
      'Q31': 'Yes, Floating',
      'Q32': 'No',
      'Q33': 'Yes, Walking',
      'Q3A': 'Yes, Floating',
      //
      'Q4': 'How many stars are there?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '3',
      //
      'Q5': 'Is there a comet? What color is it?',
      'Q51': 'Yes, White',
      'Q52': 'No',
      'Q53': 'Yes, Blue',
      'Q5A': 'Yes, White',
      //
      'Q6': 'How many moons can you see?',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': 'Are there any satellites? How many?',
      'Q71': 'Yes, 1',
      'Q72': 'Yes, 2',
      'Q73': 'No',
      'Q7A': 'Yes, 1',
      //
      'Q8': 'What color is the space station?',
      'Q81': 'White',
      'Q82': 'Black',
      'Q83': 'Red',
      'Q8A': 'White',
      //
      'Q9': 'How many space rocks are there?',
      'Q91': '1',
      'Q92': '2',
      'Q93': '3',
      'Q9A': '2',
      //
      'Q10': 'What color is the galaxy?',
      'Q101': 'Red',
      'Q102': 'Blue',
      'Q103': 'Green',
      'Q10A': 'Blue',
    },
    '11': {
      'Q1': 'How many lions are there?',
      'Q11': '1',
      'Q12': '2',
      'Q13': '0',
      'Q1A': '0',
      //
      'Q2': 'What color is the tiger?',
      'Q21': 'Orange',
      'Q22': 'Yellow',
      'Q23': 'White',
      'Q2A': 'Orange',
      //
      'Q3': 'Are there any birds? How many?',
      'Q31': 'Yes, 1',
      'Q32': 'Yes, 2',
      'Q33': 'No',
      'Q3A': 'Yes, 2',
      //
      'Q4': 'How many different enclosures are visible?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '3',
      //
      'Q5': 'Is there a zookeeper? What is he/she doing?',
      'Q51': 'Yes, Feeding animals',
      'Q52': 'No',
      'Q53': 'Yes, Cleaning',
      'Q5A': 'Yes, Feeding animals',
      //
      'Q6': 'How many visitors are there?',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '3',
      //
      'Q7': 'Are there any monkeys? What are they doing?',
      'Q71': 'Yes, Playing',
      'Q72': 'No',
      'Q73': 'Yes, Sleeping',
      'Q7A': 'Yes, Playing',
      //
      'Q8': 'What color is the elephant?',
      'Q81': 'Gray',
      'Q82': 'White',
      'Q83': 'Black',
      'Q8A': 'Gray',
      //
      'Q9': 'How many benches are there?',
      'Q91': '1',
      'Q92': '2',
      'Q93': '3',
      'Q9A': '2',
      //
      'Q10': 'Are there any signs? What do they say?',
      'Q101': 'Yes, Do not feed animals',
      'Q102': 'No',
      'Q103': 'Yes, Welcome',
      'Q10A': 'Yes, Do not feed animals',
    },
    '12': {
      'Q1': 'How many stalls are there?',
      'Q11': '1',
      'Q12': '2',
      'Q13': '3',
      'Q1A': '3',
      //
      'Q2': 'What fruits are being sold?',
      'Q21': 'Apples and Oranges',
      'Q22': 'Bananas and Grapes',
      'Q23': 'Pineapples and Mangoes',
      'Q2A': 'Apples and Oranges',
      //
      'Q3': 'How many people are shopping?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '2',
      //
      'Q4': 'What color are the vendor\'s tents?',
      'Q41': 'Red',
      'Q42': 'Blue',
      'Q43': 'Yellow',
      'Q4A': 'Red',
      //
      'Q5': 'Are there any animals? What kind?',
      'Q51': 'Yes, Dogs',
      'Q52': 'No',
      'Q53': 'Yes, Cats',
      'Q5A': 'Yes, Dogs',
      //
      'Q6': 'How many baskets can you see?',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '2',
      //
      'Q7': 'What color are the vegetables?',
      'Q71': 'Green',
      'Q72': 'Red',
      'Q73': 'Yellow',
      'Q7A': 'Green',
      //
      'Q8': 'Is there a flower stall? What flowers are there?',
      'Q81': 'Yes, Roses',
      'Q82': 'No',
      'Q83': 'Yes, Tulips',
      'Q8A': 'Yes, Roses',
      //
      'Q9': 'How many children are there?',
      'Q91': '1',
      'Q92': '2',
      'Q93': '3',
      'Q9A': '2',
      //
      'Q10': 'Are there any bicycles parked nearby?',
      'Q101': 'Yes',
      'Q102': 'No',
      'Q103': 'Maybe',
      'Q10A': 'Yes',
    },
    '13': {
      'Q1': 'How many cacti are there?',
      'Q11': '1',
      'Q12': '2',
      'Q13': '3',
      'Q1A': '2',
      //
      'Q2': 'Is there an oasis? What is around it?',
      'Q21': 'Yes, Trees',
      'Q22': 'No',
      'Q23': 'Yes, Rocks',
      'Q2A': 'Yes, Trees',
      //
      'Q3': 'What color is the sand?',
      'Q31': 'Yellow',
      'Q32': 'White',
      'Q33': 'Red',
      'Q3A': 'Yellow',
      //
      'Q4': 'How many animals are visible?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '3',
      //
      'Q5': 'Is there a caravan? How many camels are there?',
      'Q51': 'Yes, 2',
      'Q52': 'No',
      'Q53': 'Yes, 3',
      'Q5A': 'Yes, 2',
      //
      'Q6': 'Are there any people? What are they doing?',
      'Q61': 'Yes, Walking',
      'Q62': 'No',
      'Q63': 'Yes, Sitting',
      'Q6A': 'Yes, Walking',
      //
      'Q7': 'How many camels are there?',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': 'How many rocks are there?',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '2',
      //
      'Q9': 'Are there any dunes? How many?',
      'Q91': 'Yes, 1',
      'Q92': 'Yes, 2',
      'Q93': 'No',
      'Q9A': 'Yes, 2',
      //
      'Q10': 'Is there a sunset? What colors are in the sky?',
      'Q101': 'Yes, Red and Orange',
      'Q102': 'No',
      'Q103': 'Yes, Pink and Purple',
      'Q10A': 'Yes, Red and Orange',
    },
    '14': {
      'Q1': 'How many fish are there?',
      'Q11': '1',
      'Q12': '2',
      'Q13': '3',
      'Q1A': '3',
      //
      'Q2': 'What color is the coral?',
      'Q21': 'Red',
      'Q22': 'Blue',
      'Q23': 'Yellow',
      'Q2A': 'Red',
      //
      'Q3': 'Are there any divers? How many?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '2',
      //
      'Q4': 'How many different types/colors of fish can you see?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '3',
      //
      'Q5': 'Is there a shark? What color is it?',
      'Q51': 'Yes, Gray',
      'Q52': 'No',
      'Q53': 'Yes, Blue',
      'Q5A': 'Yes, Gray',
      //
      'Q6': 'How many sea plants are there?',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '3',
      //
      'Q7': 'Are there any turtles? How many?',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': 'What color is the water?',
      'Q81': 'Blue',
      'Q82': 'Green',
      'Q83': 'Gray',
      'Q8A': 'Blue',
      //
      'Q9': 'How many bubbles are there?',
      'Q91': '1',
      'Q92': '2',
      'Q93': '3',
      'Q9A': '3',
      //
      'Q10': 'Are there any shells? How many?',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    '15': {
      'Q1': 'How many paintings are displayed on the walls?',
      'Q11': '1',
      'Q12': '2',
      'Q13': '3',
      'Q1A': '3',
      //
      'Q2': 'What color is the sculpture in the center of the room?',
      'Q21': 'Red',
      'Q22': 'Blue',
      'Q23': 'White',
      'Q2A': 'White',
      //
      'Q3': 'How many visitors are looking at the exhibits?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '2',
      //
      'Q4': 'Are there any interactive displays? How many?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'What is the main theme of the museum hall (e.g., art, history, science)?',
      'Q51': 'Art',
      'Q52': 'History',
      'Q53': 'Science',
      'Q5A': 'Art',
      //
      'Q6': 'Are there any children in the museum? How many?',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '2',
      //
      'Q7': 'How many benches are there for visitors to sit on?',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': 'Are there any signs or placards? What information do they provide?',
      'Q81': 'Yes, Exhibit Information',
      'Q82': 'No',
      'Q83': 'Yes, Directions',
      'Q8A': 'Yes, Exhibit Information',
      //
      'Q9': 'Is there a guide or museum staff present? What are they doing?',
      'Q91': 'Yes, Giving a Tour',
      'Q92': 'No',
      'Q93': 'Yes, Answering Questions',
      'Q9A': 'Yes, Giving a Tour',
      //
      'Q10': 'What is the predominant color of the walls in the museum hall?',
      'Q101': 'Red',
      'Q102': 'Blue',
      'Q103': 'White',
      'Q10A': 'White',
    },
  };

  /*Map Questions = {
    '1': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '2': {
      'Q1': 'What color was the main building?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many bicycles were parked nearby? One orange and one big grey ',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'Were there any benches? How many? ',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': ' What color was the sky? ',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'Were there any clouds? What shape were they?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was there a playground? What equipment did it have? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many people were sitting on benches?',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' Was there a water fountain? What color was it? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Were there any streetlights? How many? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' Were there any signs? What did they say?',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '3': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '4': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '5': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '6': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '7': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '8': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '9': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '10': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '11': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '12': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '13': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '14': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
    '15': {
      'Q1': 'What color was the door of the house?',
      'Q11': 'Blue',
      'Q12': 'Red',
      'Q13': 'Turquoise',
      'Q1A': 'Blue',
      //
      'Q2': 'How many were the children?',
      'Q21': '3',
      'Q22': '5',
      'Q23': '7',
      'Q2A': '5',
      //
      'Q3': 'How many children did wear the green scarf?',
      'Q31': '1',
      'Q32': '2',
      'Q33': '3',
      'Q3A': '1',
      //
      'Q4': 'How many children were sitting?',
      'Q41': '1',
      'Q42': '2',
      'Q43': '3',
      'Q4A': '2',
      //
      'Q5': 'How many were standing?',
      'Q51': '1',
      'Q52': '2',
      'Q53': '3',
      'Q5A': '1',
      //
      'Q6': ' Was the blonde-haired child sitting? ',
      'Q61': '1',
      'Q62': '2',
      'Q63': '3',
      'Q6A': '1',
      //
      'Q7': ' How many blue cars did the children play with? ',
      'Q71': '1',
      'Q72': '2',
      'Q73': '3',
      'Q7A': '2',
      //
      'Q8': ' How many trucks were the children playing with? ',
      'Q81': '1',
      'Q82': '2',
      'Q83': '3',
      'Q8A': '3',
      //
      'Q9': 'Was the door open? ',
      'Q91': 'Wide open',
      'Q92': 'Closed',
      'Q93': 'Slightly open',
      'Q9A': 'Closed',
      //
      'Q10': ' How many floors did the house have? ',
      'Q101': '1',
      'Q102': '2',
      'Q103': '3',
      'Q10A': '2',
    },
    //
    //
  };*/
}
